# Generated by Django 2.0.2 on 2018-03-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='session_key',
            field=models.CharField(default='', max_length=50, verbose_name='会话密钥'),
            preserve_default=False,
        ),
    ]
