# Generated by Django 2.0.2 on 2018-03-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_userprofile_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invite_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='邀请人'),
        ),
    ]
