# Generated by Django 2.0.2 on 2018-03-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_userprofile_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='base',
            field=models.IntegerField(default=0, verbose_name='基础积分'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='times',
            field=models.IntegerField(default=1, verbose_name='积分倍数'),
        ),
    ]
