# Generated by Django 2.0.2 on 2018-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_auto_20180306_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf', models.CharField(max_length=20, unique=True, verbose_name='唯一标识')),
                ('name', models.CharField(max_length=20, verbose_name='活动名称')),
                ('point', models.IntegerField(verbose_name='积分点数')),
                ('is_multi', models.BooleanField(default=False, verbose_name='是否可多次完成')),
            ],
            options={
                'verbose_name': '任务基础信息',
                'verbose_name_plural': '任务基础信息',
            },
        ),
    ]
