# Generated by Django 2.0.2 on 2018-03-07 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserManagement', '0006_statisticaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('point', models.IntegerField(verbose_name='增减点数')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.TaskInfo', verbose_name='任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分记录',
                'verbose_name_plural': '积分记录',
            },
        ),
        migrations.CreateModel(
            name='SignRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '签到记录',
                'verbose_name_plural': '签到记录',
            },
        ),
        migrations.CreateModel(
            name='WxRunRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('c_date', models.DateField(verbose_name='日期')),
                ('step', models.IntegerField(verbose_name='步数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '微信运动',
                'verbose_name_plural': '微信运动',
            },
        ),
        migrations.AlterUniqueTogether(
            name='wxrunrecord',
            unique_together={('user', 'c_date')},
        ),
    ]
