# Generated by Django 2.0.2 on 2018-03-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_auto_20180307_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='用户头像'),
        ),
    ]
