# Generated by Django 2.0.2 on 2018-03-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0008_auto_20180307_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_mp',
            field=models.BooleanField(default=False, verbose_name='公众号关注'),
        ),
    ]
