# Generated by Django 2.0.2 on 2018-03-26 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserManagement', '0009_userprofile_is_mp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('audit', '审核中'), ('success', '审核成功'), ('failed', '审核失败')], max_length=20, verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '眼底片审核',
                'verbose_name_plural': '眼底片审核',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=50, verbose_name='文件名称')),
                ('path', models.CharField(max_length=100, verbose_name='文件路径')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '上传文件列表',
                'verbose_name_plural': '上传文件列表',
            },
        ),
        migrations.AddField(
            model_name='eyeimage',
            name='ufs',
            field=models.ManyToManyField(to='UserManagement.UploadFile', verbose_name='待审核文件'),
        ),
        migrations.AddField(
            model_name='eyeimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
