# Generated by Django 2.0.2 on 2018-03-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0010_auto_20180326_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='name',
            field=models.TextField(verbose_name='文件名称'),
        ),
    ]
