# Generated by Django 2.0.2 on 2018-03-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0011_auto_20180326_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='WXToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('token', models.TextField(verbose_name='AccessToken')),
                ('t_type', models.CharField(choices=[('pb', '公众号'), ('pg', '小程序')], max_length=10, verbose_name='类型')),
            ],
            options={
                'verbose_name': 'AccessToken',
                'verbose_name_plural': 'AccessToken',
            },
        ),
    ]
