# Generated by Django 2.0.2 on 2018-03-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0014_userprofile_unionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('openid', models.CharField(max_length=35, verbose_name='微信唯一标识')),
                ('unionid', models.CharField(max_length=50, verbose_name='全局唯一标识')),
                ('msg_type', models.CharField(choices=[('event', '事件'), ('txt', '文本消息'), ('image', '图片消息'), ('voice', '语音消息'), ('video', '视频消息'), ('shortvideo', '小视频消息'), ('location', '地理位置'), ('link', '链接')], default='event', max_length=20, verbose_name='类型')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女'), (0, '未知')], default=0, verbose_name='性别')),
                ('avatar', models.TextField(blank=True, default='', null=True, verbose_name='用户头像')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='所在国家')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='所在省份')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='所在城市')),
                ('language', models.CharField(blank=True, max_length=50, verbose_name='语言')),
                ('subscribe_scene', models.CharField(choices=[('ADD_SCENE_SEARCH', '公众号搜索'), ('ADD_SCENE_ACCOUNT_MIGRATION', '公众号迁移'), ('ADD_SCENE_PROFILE_CARD', '名片分享'), ('ADD_SCENE_QR_CODE', '扫描二维码'), ('ADD_SCENEPROFILE LINK', '图文页内名称点击'), ('ADD_SCENE_PROFILE_ITEM', '图文页右上角菜单'), ('ADD_SCENE_PAID', '支付后关注'), ('ADD_SCENE_OTHERS', '其他')], max_length=20, verbose_name='关注来源')),
            ],
            options={
                'verbose_name': '公众号关注',
                'verbose_name_plural': '公众号关注',
            },
        ),
    ]
