# Generated by Django 2.0.2 on 2018-03-27 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0015_wechatsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatsubscription',
            name='s_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 27, 16, 21, 46, 686334), help_text='多次关注，取最后一次关注时间', verbose_name='关注时间'),
            preserve_default=False,
        ),
    ]
