# Generated by Django 2.0.2 on 2018-03-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0016_wechatsubscription_s_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wechatsubscription',
            unique_together={('openid', 'unionid')},
        ),
    ]
