# Generated by Django 2.0.2 on 2018-03-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0017_auto_20180327_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatsubscription',
            name='subscribe_scene',
            field=models.TextField(choices=[('ADD_SCENE_SEARCH', '公众号搜索'), ('ADD_SCENE_ACCOUNT_MIGRATION', '公众号迁移'), ('ADD_SCENE_PROFILE_CARD', '名片分享'), ('ADD_SCENE_QR_CODE', '扫描二维码'), ('ADD_SCENEPROFILE LINK', '图文页内名称点击'), ('ADD_SCENE_PROFILE_ITEM', '图文页右上角菜单'), ('ADD_SCENE_PAID', '支付后关注'), ('ADD_SCENE_OTHERS', '其他')], verbose_name='关注来源'),
        ),
    ]
