# Generated by Django 2.0.2 on 2018-03-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0020_userprofile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatsubscription',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='昵称'),
        ),
    ]
