# Generated by Django 2.0.3 on 2018-05-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='用户id', max_length=25, verbose_name='uid')),
                ('nickName', models.CharField(help_text='用户昵称', max_length=25, verbose_name='nickName')),
                ('country', models.CharField(help_text='所属地区', max_length=25, verbose_name='country')),
            ],
        ),
    ]
