# Generated by Django 2.0.3 on 2018-05-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0002_auto_20180503_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='loginTime',
            field=models.CharField(default='default', help_text='最后一次登录时间', max_length=25, verbose_name='loginTime'),
        ),
        migrations.AddField(
            model_name='userbase',
            name='uid',
            field=models.CharField(default='openid', help_text='用户id', max_length=25, verbose_name='uid'),
        ),
    ]
